const paragraphs = [
    "The older man shuffled slowly down the dirt road, a faded baseball cap pulled low over his eyes to shield them from the sun/'s rays. He wore overalls and a flannel shirt, his hands calloused from years of hard work in the fields. His face was craggy but kind- a life filled with stories hidden beneath the wrinkles that framed his eyes. I watched him as he walked, his steps light despite the weight of all he had seen",

    "The lush meadow was blanketed in soft green grass, punctuated with wildflowers in all rainbow colours. The sun shone brightly in the sky, warming everything beneath it with its gentle rays. In the distance, a stream babbled peacefully as birds chirped their songs from the trees that lined it. The air was heavy with the sweet scent of honey, and I closed my eyes to take in all of its beauty.",

    "The ancient ruins surrounded a vast desert, their sand-covered stones looking out over miles of wind-swept dunes. I walked through the crumbling archway and into the courtyard, taking in the eerie silence that pervaded the entire site.The sun beat down from above, its rays glinting off broken columns and walls that told stories of a forgotten time. Here was evidence of an ancient civilization that had disappeared into history",

    "The decrepit old mansion stood atop a hill like a silent sentinel watching over the valley below. Tall windows stared blankly from the walls, their glass panes long since shattered. The grounds were overgrown with weeds and wildflowers, a testament to the fact that no one had set foot here in many years. I stepped through the doorway and into what felt like an entirely different world- a place filled with secrets and stories waiting to be discovered.",

    "The silver moon shone brightly against the night sky, its reflection glittering on the still surface of the lake below. Fireflies sparkled around me like stars fallen from the heavens, their lights twinkling in tandem with those of distant galaxies. Crickets chirped softly as they scuttled across my path while owls hooted in the distance. Everything felt peaceful and calm, as if time had stopped to admire this magical moment.",

    "The beach was a tranquil paradise, soft white sand stretching out towards an endless blue horizon. The waves crashed gently against the shore, their foamy spray cooling my skin under the hot afternoon sun.Seagulls hovered overhead, crying as they searched for food along the shoreline. Everywhere I looked, there was beauty; everything seemed perfect at that moment, from the towering palm trees to the sparkling sea below.",

    "The sun was setting, painting the sky in vibrant shades of orange, pink and purple. The clouds were streaked with golden light, completing the brilliant spectacle that was taking place all around me.I stopped to take it all in, feeling deep gratitude and awe at witnessing such a beautiful sight. All my worries seemed so far away at that moment; here, nothing else mattered but enjoying this fantastic view.",

    "The dusty roads wound their way through the rolling hills of the countryside, lined by ancient trees whose roots had grown deep over centuries. Wildflowers flourished in splashes of colour against the backdrop of green fields and blue sky.The air was sweet with the scent of fresh-cut hay and the buzzing of bees. There was a beauty that could only be found in nature, a timeless reminder of the power and magnificence of the world around us.",

    "The desert stretched out before me, a vast expanse of red sand and sun-bleached rocks. The heat was oppressive but calming, the warm breeze carrying an earthy scent. In the distance, I could see dust devils whirling across the dunes, throwing up clouds of golden sand in their wake. It felt like a place stuck in time, where one could take refuge from the frenetic pace of modern life and find solace in nature",

    "The forest was alive with sound and colour; birdsong filled the air while shafts of sunlight pierced through the canopy above, dappling the ground below with splashes of gold. The trees stood tall and proud, their leaves rustling in the gentle breeze. Everywhere I looked, there was evidence of life; from the scurrying squirrels to the buzzing insects, it seemed as if everything had been frozen in perfect harmony and balance. It was an enchanting sight that made me feel profoundly alive.",

    "The lake shimmered in the afternoon light, its still waters reflecting the clouds above. The sun shone brightly in a deep blue sky, making everything around me seem alive and vibrant. I could feel the warmth of the sand beneath my feet as I walked along the beach, watching the waves lap against the shoreline. Everywhere I looked, there was beauty; from the towering mountains on either side to the lush greenery that covered them, it was an idyllic setting that filled my heart with joy."
]